name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.5

      - name: Build for linux/amd64
        run: GOOS=linux GOARCH=amd64 go build -v -ldflags="-s -w" -o opt/munager_linux_amd64 .

      - name: Build for windows/amd64
        run: GOOS=windows GOARCH=amd64 go build -v -ldflags="-s -w" -o opt/munager_windows_amd64.exe .

      - name: Build for android/arm64
        run: GOOS=android GOARCH=arm64 go build -v -ldflags="-s -w" -o opt/munager_android_arm64 .

      - name: Upload compiled artifact
        uses: actions/upload-artifact@v2
        with:
          name: munager_executables
          path: opt/