name: Build binary files

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.5

      - name: Build for linux/amd64
        run: GOOS=linux GOARCH=amd64 go build -v -ldflags="-s -w" -o opt/munager_linux_amd64 .

      - name: Build for windows/amd64
        run: GOOS=windows GOARCH=amd64 go build -v -ldflags="-s -w" -o opt/munager_windows_amd64.exe .

      - name: Build for android/arm64
        run: GOOS=android GOARCH=arm64 go build -v -ldflags="-s -w" -o opt/munager_android_arm64 .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            This is an automated release of the binary files for version ${{ github.ref }}.
          draft: false
          prerelease: false

      - name: Upload compiled artifact
        uses: actions/upload-artifact@v2
        with:
          name: munager_executables
          path: opt/

      - name: Attach binaries to release
        id: attach_binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: opt/
          asset_name: munager_executables
          asset_content_type: application/octet-stream
